Basic support for a typecheck command
hypothesis/cookiecutters pull request #163
Opened 2024-01-08 15:57 UTC by marcospri

Very basic support for `typecheck`.

It doesn't introduce any configuration options for mypy until/if we use them in a few projects.

2024-01-09 10:16 UTC, seanh requested changes

2024-01-15 10:49 UTC, marcospri commented on _shared/project/tox.ini
> +    typecheck: mypy lms
Nah, I don't think is worth the effort there, at least not yet. We'd have to add tons of disables to keep it clean and the test code tends to be more "dynamic."

2024-01-18 11:21 UTC, seanh requested changes
It looks to me like a `requirements/typecheck.in` file is missing

2024-01-18 11:21 UTC, seanh commented on _shared/project/tox.ini
> +    typecheck: mypy lms
I think you need to remove the `{% if %}` from `tox.ini` here as well. Currently it's adding `make typecheck` to `Makefile` but not adding the stuff to `tox.ini` so the command fails

2024-01-18 11:21 UTC, seanh commented on pyapp/cookiecutter.json
> +    "typecheck": ["no", "yes"],
If we're removing the `{% if %}` and just adding `make typecheck` and `tox -e typecheck` to all projects, then we can remove this

2024-01-18 11:24 UTC, seanh commented
To test this:

```terminal
cd /tmp
git clone https://github.com/hypothesis/test-pyramid-app.git
cd test-pyramid-app
make template checkout=basic-mypy-option
make typecheck
```

`make` currently crashes with `ERROR: unknown environment 'typecheck'`. I think there's at least two problems:

1. The `Makefile` changes are added unconditionally, but the `tox.ini` changes are only added if `"typecheck": "yes"` is in `cookiecutter.json`
2. `requirements/typecheck.in` is missing

I think we can get rid of the `typecheck` cookiecutter option entirely and just add the typecheck stuff to `Makefile`, `tox.ini` and `requirements/` unconditionally

2024-02-01 09:38 UTC, marcospri commented
I'm having trouble with the requirements side of this:

- Are requirements.in files copied from the template on existing projects? I can imagine that it won't try existing ones.

- Even if it did copy them, would we need to run `make requirements` on the target projects to generate the .txt file?

2024-02-01 11:06 UTC, seanh requested changes
The `pyapp` and `pyramid-app` folders need to contain symlinks to the new `typecheck.in` file (but not the `pypackage` folder since packages don't have requirements files). This is what the `_shared` folder is: a folder full of shared templates for the `pypackage`, `pyapp`, and `pyramid-app` folders to symlink to. Currently it's not actually adding that file to any projects. (The symlinks are horrible. More recent versions of cookiecutter have added support for Jinja2 inheritance instead where you can have shared base templates that templates in each of the individual cookiecutters inherit from. That's gonna be much nicer, but it'll be a job to migrate our cookiecutters from symlinks to inheritance.)

In `test-pypackage` I'm getting:

```
ERROR: InvocationError for command could not find executable mypy
```

You need to add this to the `deps` section in `tox.ini`:

```ini
deps = 
  ...
  typecheck: mypy
```

(Yes, it has to be unpinned.)

This should be done for packages only, not apps, since apps have the dependencies in their requirements files. There's already a [section in the `tox.ini` template](https://github.com/hypothesis/cookiecutters/blob/933c38d6bcf1660bcc71c31bfa3c4b443ef6569d/_shared/project/tox.ini#L67-L84) for packages-only dependencies.

2024-02-06 10:44 UTC, seanh approved these changes
:+1: Works for me

2024-02-06 12:41 UTC, merged